spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/FaxBoy/config-cloud
          username: sl166199@163.com
          password:
          timeout: 5
          default-label: master

#指定注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 9100