##################  所有profile共有的配置  #################


###################  swagger配置  ###################
wavenet:
  swagger-open: false #是否开启swagger (true/false)

###################  spring配置  ###################
spring:
  profiles:
    active: prod
  thymeleaf:
    prefix: classpath:/templates/