###################  开发环境的profile  ###################
server:
  port: 8081 #程序端口

spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://192.168.72.34:3306/mouse?useSSL=true&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: root
  aop:
    proxy-target-class: true
  elasticsearch:
    rest:
      uris: ["10.211.55.4:9200","10.211.55.5:9200"]

#elasticsearch:
#  ip: 10.211.55.4:9200,10.211.55.5:9200

logging:
  level.root: info
  level.com.wavenet: debug
  path: /logs/mouse/
  file: springboot.log

mybatis-plus:
  mapper-locations: classpath:mapping/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.mouse.springbootshiro.dao
  global-config:
    # 数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: ignored
      #驼峰下划线转换
      db-column-underline: true
      #刷新mapper 调试神器
      refresh-mapper: true
    # 原生配置
    configuration:
      map-underscore-to-camel-case: true
      cache-enabled: false #配置的缓存的全局开关
      lazyLoadingEnabled: false #延时加载的开关
      multipleResultSetsEnabled: false #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
#      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用